<?php
/**
 *
 * Part of the QCubed PHP framework.
 *
 * @license MIT
 *
 */

namespace QCubed\Bootstrap;

use QCubed\Control\ControlBase;
use QCubed\Exception\Caller;

/**
 * If you are compiling your own bootstrap CSS file, point to it with the QCUBED_BOOTSTRAP_CSS definition. Otherwise, it will take
 * the default one from the bootstrap distribution.
 */
if (!defined('QCUBED_BOOTSTRAP_CSS')) {
    define('QCUBED_BOOTSTRAP_CSS', QCUBED_VENDOR_URL . '/twbs/bootstrap/dist/css/bootstrap.min.css');
}

/**
 * Define QCUBED_BOOTSTRAP_JS to handle your own loading of the bootstrap JS files. Bootstrap includes a minimized version
 * and a non-minimized version.
 */
if (!defined('QCUBED_BOOTSTRAP_JS')) {
    define('QCUBED_BOOTSTRAP_JS', QCUBED_VENDOR_URL . '/twbs/bootstrap/dist/js/bootstrap.min.js');
}

if (!defined('QCUBED_BOOTSTRAP_ASSETS_URL')) {
    define('QCUBED_BOOTSTRAP_ASSETS_URL', dirname(QCUBED_BASE_URL) . '/bootstrap/assets');
}


/**
 * Class Bootstrap
 *
 * @package QCubed\Bootstrap
 * @was QCubed\Plugin\Bootstrap
 */
abstract class Bootstrap
{
    /** Generated by GlyphiconGen.php */
    const string GLYPHICON_ASTERISK = "glyphicon-asterisk";
    const string GLYPHICON_PLUS = "glyphicon-plus";
    const string GLYPHICON_EURO = "glyphicon-euro";
    const string GLYPHICON_MINUS = "glyphicon-minus";
    const string GLYPHICON_CLOUD = "glyphicon-cloud";
    const string GLYPHICON_ENVELOPE = "glyphicon-envelope";
    const string GLYPHICON_PENCIL = "glyphicon-pencil";
    const string GLYPHICON_GLASS = "glyphicon-glass";
    const string GLYPHICON_MUSIC = "glyphicon-music";
    const string GLYPHICON_SEARCH = "glyphicon-search";
    const string GLYPHICON_HEART = "glyphicon-heart";
    const string GLYPHICON_STAR = "glyphicon-star";
    const string GLYPHICON_STAR_EMPTY = "glyphicon-star-empty";
    const string GLYPHICON_USER = "glyphicon-user";
    const string GLYPHICON_FILM = "glyphicon-film";
    const string GLYPHICON_TH_LARGE = "glyphicon-th-large";
    const string GLYPHICON_TH = "glyphicon-th";
    const string GLYPHICON_TH_LIST = "glyphicon-th-list";
    const string GLYPHICON_OK = "glyphicon-ok";
    const string GLYPHICON_REMOVE = "glyphicon-remove";
    const string GLYPHICON_ZOOM_IN = "glyphicon-zoom-in";
    const string GLYPHICON_ZOOM_OUT = "glyphicon-zoom-out";
    const string GLYPHICON_OFF = "glyphicon-off";
    const string GLYPHICON_SIGNAL = "glyphicon-signal";
    const string GLYPHICON_COG = "glyphicon-cog";
    const string GLYPHICON_TRASH = "glyphicon-trash";
    const string GLYPHICON_HOME = "glyphicon-home";
    const string GLYPHICON_FILE = "glyphicon-file";
    const string GLYPHICON_TIME = "glyphicon-time";
    const string GLYPHICON_ROAD = "glyphicon-road";
    const string GLYPHICON_DOWNLOAD_ALT = "glyphicon-download-alt";
    const string GLYPHICON_DOWNLOAD = "glyphicon-download";
    const string GLYPHICON_UPLOAD = "glyphicon-upload";
    const string GLYPHICON_INBOX = "glyphicon-inbox";
    const string GLYPHICON_PLAY_CIRCLE = "glyphicon-play-circle";
    const string GLYPHICON_REPEAT = "glyphicon-repeat";
    const string GLYPHICON_REFRESH = "glyphicon-refresh";
    const string GLYPHICON_LIST_ALT = "glyphicon-list-alt";
    const string GLYPHICON_LOCK = "glyphicon-lock";
    const string GLYPHICON_FLAG = "glyphicon-flag";
    const string GLYPHICON_HEADPHONES = "glyphicon-headphones";
    const string GLYPHICON_VOLUME_OFF = "glyphicon-volume-off";
    const string GLYPHICON_VOLUME_DOWN = "glyphicon-volume-down";
    const string GLYPHICON_VOLUME_UP = "glyphicon-volume-up";
    const string GLYPHICON_QRCODE = "glyphicon-qrcode";
    const string GLYPHICON_BARCODE = "glyphicon-barcode";
    const string GLYPHICON_TAG = "glyphicon-tag";
    const string GLYPHICON_TAGS = "glyphicon-tags";
    const string GLYPHICON_BOOK = "glyphicon-book";
    const string GLYPHICON_BOOKMARK = "glyphicon-bookmark";
    const string GLYPHICON_PRINT = "glyphicon-print";
    const string GLYPHICON_CAMERA = "glyphicon-camera";
    const string GLYPHICON_FONT = "glyphicon-font";
    const string GLYPHICON_BOLD = "glyphicon-bold";
    const string GLYPHICON_ITALIC = "glyphicon-italic";
    const string GLYPHICON_TEXT_HEIGHT = "glyphicon-text-height";
    const string GLYPHICON_TEXT_WIDTH = "glyphicon-text-width";
    const string GLYPHICON_ALIGN_LEFT = "glyphicon-align-left";
    const string GLYPHICON_ALIGN_CENTER = "glyphicon-align-center";
    const string GLYPHICON_ALIGN_RIGHT = "glyphicon-align-right";
    const string GLYPHICON_ALIGN_JUSTIFY = "glyphicon-align-justify";
    const string GLYPHICON_LIST = "glyphicon-list";
    const string GLYPHICON_INDENT_LEFT = "glyphicon-indent-left";
    const string GLYPHICON_INDENT_RIGHT = "glyphicon-indent-right";
    const string GLYPHICON_FACETIME_VIDEO = "glyphicon-facetime-video";
    const string GLYPHICON_PICTURE = "glyphicon-picture";
    const string GLYPHICON_MAP_MARKER = "glyphicon-map-marker";
    const string GLYPHICON_ADJUST = "glyphicon-adjust";
    const string GLYPHICON_TINT = "glyphicon-tint";
    const string GLYPHICON_EDIT = "glyphicon-edit";
    const string GLYPHICON_SHARE = "glyphicon-share";
    const string GLYPHICON_CHECK = "glyphicon-check";
    const string GLYPHICON_MOVE = "glyphicon-move";
    const string GLYPHICON_STEP_BACKWARD = "glyphicon-step-backward";
    const string GLYPHICON_FAST_BACKWARD = "glyphicon-fast-backward";
    const string GLYPHICON_BACKWARD = "glyphicon-backward";
    const string GLYPHICON_PLAY = "glyphicon-play";
    const string GLYPHICON_PAUSE = "glyphicon-pause";
    const string GLYPHICON_STOP = "glyphicon-stop";
    const string GLYPHICON_FORWARD = "glyphicon-forward";
    const string GLYPHICON_FAST_FORWARD = "glyphicon-fast-forward";
    const string GLYPHICON_STEP_FORWARD = "glyphicon-step-forward";
    const string GLYPHICON_EJECT = "glyphicon-eject";
    const string GLYPHICON_CHEVRON_LEFT = "glyphicon-chevron-left";
    const string GLYPHICON_CHEVRON_RIGHT = "glyphicon-chevron-right";
    const string GLYPHICON_PLUS_SIGN = "glyphicon-plus-sign";
    const string GLYPHICON_MINUS_SIGN = "glyphicon-minus-sign";
    const string GLYPHICON_REMOVE_SIGN = "glyphicon-remove-sign";
    const string GLYPHICON_OK_SIGN = "glyphicon-ok-sign";
    const string GLYPHICON_QUESTION_SIGN = "glyphicon-question-sign";
    const string GLYPHICON_INFO_SIGN = "glyphicon-info-sign";
    const string GLYPHICON_SCREENSHOT = "glyphicon-screenshot";
    const string GLYPHICON_REMOVE_CIRCLE = "glyphicon-remove-circle";
    const string GLYPHICON_OK_CIRCLE = "glyphicon-ok-circle";
    const string GLYPHICON_BAN_CIRCLE = "glyphicon-ban-circle";
    const string GLYPHICON_ARROW_LEFT = "glyphicon-arrow-left";
    const string GLYPHICON_ARROW_RIGHT = "glyphicon-arrow-right";
    const string GLYPHICON_ARROW_UP = "glyphicon-arrow-up";
    const string GLYPHICON_ARROW_DOWN = "glyphicon-arrow-down";
    const string GLYPHICON_SHARE_ALT = "glyphicon-share-alt";
    const string GLYPHICON_RESIZE_FULL = "glyphicon-resize-full";
    const string GLYPHICON_RESIZE_SMALL = "glyphicon-resize-small";
    const string GLYPHICON_EXCLAMATION_SIGN = "glyphicon-exclamation-sign";
    const string GLYPHICON_GIFT = "glyphicon-gift";
    const string GLYPHICON_LEAF = "glyphicon-leaf";
    const string GLYPHICON_FIRE = "glyphicon-fire";
    const string GLYPHICON_EYE_OPEN = "glyphicon-eye-open";
    const string GLYPHICON_EYE_CLOSE = "glyphicon-eye-close";
    const string GLYPHICON_WARNING_SIGN = "glyphicon-warning-sign";
    const string GLYPHICON_PLANE = "glyphicon-plane";
    const string GLYPHICON_CALENDAR = "glyphicon-calendar";
    const string GLYPHICON_RANDOM = "glyphicon-random";
    const string GLYPHICON_COMMENT = "glyphicon-comment";
    const string GLYPHICON_MAGNET = "glyphicon-magnet";
    const string GLYPHICON_CHEVRON_UP = "glyphicon-chevron-up";
    const string GLYPHICON_CHEVRON_DOWN = "glyphicon-chevron-down";
    const string GLYPHICON_RETWEET = "glyphicon-retweet";
    const string GLYPHICON_SHOPPING_CART = "glyphicon-shopping-cart";
    const string GLYPHICON_FOLDER_CLOSE = "glyphicon-folder-close";
    const string GLYPHICON_FOLDER_OPEN = "glyphicon-folder-open";
    const string GLYPHICON_RESIZE_VERTICAL = "glyphicon-resize-vertical";
    const string GLYPHICON_RESIZE_HORIZONTAL = "glyphicon-resize-horizontal";
    const string GLYPHICON_HDD = "glyphicon-hdd";
    const string GLYPHICON_BULLHORN = "glyphicon-bullhorn";
    const string GLYPHICON_BELL = "glyphicon-bell";
    const string GLYPHICON_CERTIFICATE = "glyphicon-certificate";
    const string GLYPHICON_THUMBS_UP = "glyphicon-thumbs-up";
    const string GLYPHICON_THUMBS_DOWN = "glyphicon-thumbs-down";
    const string GLYPHICON_HAND_RIGHT = "glyphicon-hand-right";
    const string GLYPHICON_HAND_LEFT = "glyphicon-hand-left";
    const string GLYPHICON_HAND_UP = "glyphicon-hand-up";
    const string GLYPHICON_HAND_DOWN = "glyphicon-hand-down";
    const string GLYPHICON_CIRCLE_ARROW_RIGHT = "glyphicon-circle-arrow-right";
    const string GLYPHICON_CIRCLE_ARROW_LEFT = "glyphicon-circle-arrow-left";
    const string GLYPHICON_CIRCLE_ARROW_UP = "glyphicon-circle-arrow-up";
    const string GLYPHICON_CIRCLE_ARROW_DOWN = "glyphicon-circle-arrow-down";
    const string GLYPHICON_GLOBE = "glyphicon-globe";
    const string GLYPHICON_WRENCH = "glyphicon-wrench";
    const string GLYPHICON_TASKS = "glyphicon-tasks";
    const string GLYPHICON_FILTER = "glyphicon-filter";
    const string GLYPHICON_BRIEFCASE = "glyphicon-briefcase";
    const string GLYPHICON_FULLSCREEN = "glyphicon-fullscreen";
    const string GLYPHICON_DASHBOARD = "glyphicon-dashboard";
    const string GLYPHICON_PAPERCLIP = "glyphicon-paperclip";
    const string GLYPHICON_HEART_EMPTY = "glyphicon-heart-empty";
    const string GLYPHICON_LINK = "glyphicon-link";
    const string GLYPHICON_PHONE = "glyphicon-phone";
    const string GLYPHICON_PUSHPIN = "glyphicon-pushpin";
    const string GLYPHICON_USD = "glyphicon-usd";
    const string GLYPHICON_GBP = "glyphicon-gbp";
    const string GLYPHICON_SORT = "glyphicon-sort";
    const string GLYPHICON_SORT_BY_ALPHABET = "glyphicon-sort-by-alphabet";
    const string GLYPHICON_SORT_BY_ALPHABET_ALT = "glyphicon-sort-by-alphabet-alt";
    const string GLYPHICON_SORT_BY_ORDER = "glyphicon-sort-by-order";
    const string GLYPHICON_SORT_BY_ORDER_ALT = "glyphicon-sort-by-order-alt";
    const string GLYPHICON_SORT_BY_ATTRIBUTES = "glyphicon-sort-by-attributes";
    const string GLYPHICON_SORT_BY_ATTRIBUTES_ALT = "glyphicon-sort-by-attributes-alt";
    const string GLYPHICON_UNCHECKED = "glyphicon-unchecked";
    const string GLYPHICON_EXPAND = "glyphicon-expand";
    const string GLYPHICON_COLLAPSE_DOWN = "glyphicon-collapse-down";
    const string GLYPHICON_COLLAPSE_UP = "glyphicon-collapse-up";
    const string GLYPHICON_LOG_IN = "glyphicon-log-in";
    const string GLYPHICON_FLASH = "glyphicon-flash";
    const string GLYPHICON_LOG_OUT = "glyphicon-log-out";
    const string GLYPHICON_NEW_WINDOW = "glyphicon-new-window";
    const string GLYPHICON_RECORD = "glyphicon-record";
    const string GLYPHICON_SAVE = "glyphicon-save";
    const string GLYPHICON_OPEN = "glyphicon-open";
    const string GLYPHICON_SAVED = "glyphicon-saved";
    const string GLYPHICON_IMPORT = "glyphicon-import";
    const string GLYPHICON_EXPORT = "glyphicon-export";
    const string GLYPHICON_SEND = "glyphicon-send";
    const string GLYPHICON_FLOPPY_DISK = "glyphicon-floppy-disk";
    const string GLYPHICON_FLOPPY_SAVED = "glyphicon-floppy-saved";
    const string GLYPHICON_FLOPPY_REMOVE = "glyphicon-floppy-remove";
    const string GLYPHICON_FLOPPY_SAVE = "glyphicon-floppy-save";
    const string GLYPHICON_FLOPPY_OPEN = "glyphicon-floppy-open";
    const string GLYPHICON_CREDIT_CARD = "glyphicon-credit-card";
    const string GLYPHICON_TRANSFER = "glyphicon-transfer";
    const string GLYPHICON_CUTLERY = "glyphicon-cutlery";
    const string GLYPHICON_HEADER = "glyphicon-header";
    const string GLYPHICON_COMPRESSED = "glyphicon-compressed";
    const string GLYPHICON_EARPHONE = "glyphicon-earphone";
    const string GLYPHICON_PHONE_ALT = "glyphicon-phone-alt";
    const string GLYPHICON_TOWER = "glyphicon-tower";
    const string GLYPHICON_STATS = "glyphicon-stats";
    const string GLYPHICON_SD_VIDEO = "glyphicon-sd-video";
    const string GLYPHICON_HD_VIDEO = "glyphicon-hd-video";
    const string GLYPHICON_SUBTITLES = "glyphicon-subtitles";
    const string GLYPHICON_SOUND_STEREO = "glyphicon-sound-stereo";
    const string GLYPHICON_SOUND_DOLBY = "glyphicon-sound-dolby";
    const string GLYPHICON_SOUND51 = "glyphicon-sound-5-1";
    const string GLYPHICON_SOUND61 = "glyphicon-sound-6-1";
    const string GLYPHICON_SOUND71 = "glyphicon-sound-7-1";
    const string GLYPHICON_COPYRIGHT_MARK = "glyphicon-copyright-mark";
    const string GLYPHICON_REGISTRATION_MARK = "glyphicon-registration-mark";
    const string GLYPHICON_CLOUD_DOWNLOAD = "glyphicon-cloud-download";
    const string GLYPHICON_CLOUD_UPLOAD = "glyphicon-cloud-upload";
    const string GLYPHICON_TREE_CONIFER = "glyphicon-tree-conifer";
    const string GLYPHICON_TREE_DECIDUOUS = "glyphicon-tree-deciduous";
    const string GLYPHICON_CD = "glyphicon-cd";
    const string GLYPHICON_SAVE_FILE = "glyphicon-save-file";
    const string GLYPHICON_OPEN_FILE = "glyphicon-open-file";
    const string GLYPHICON_LEVEL_UP = "glyphicon-level-up";
    const string GLYPHICON_COPY = "glyphicon-copy";
    const string GLYPHICON_PASTE = "glyphicon-paste";
    const string GLYPHICON_DOOR = "glyphicon-door";
    const string GLYPHICON_KEY = "glyphicon-key";
    const string GLYPHICON_ALERT = "glyphicon-alert";
    const string GLYPHICON_EQUALIZER = "glyphicon-equalizer";
    const string GLYPHICON_KING = "glyphicon-king";
    const string GLYPHICON_QUEEN = "glyphicon-queen";
    const string GLYPHICON_PAWN = "glyphicon-pawn";
    const string GLYPHICON_BISHOP = "glyphicon-bishop";
    const string GLYPHICON_KNIGHT = "glyphicon-knight";
    const string GLYPHICON_BABY_FORMULA = "glyphicon-baby-formula";
    const string GLYPHICON_TENT = "glyphicon-tent";
    const string GLYPHICON_BLACKBOARD = "glyphicon-blackboard";
    const string GLYPHICON_BED = "glyphicon-bed";
    const string GLYPHICON_APPLE = "glyphicon-apple";
    const string GLYPHICON_ERASE = "glyphicon-erase";
    const string GLYPHICON_HOURGLASS = "glyphicon-hourglass";
    const string GLYPHICON_LAMP = "glyphicon-lamp";
    const string GLYPHICON_DUPLICATE = "glyphicon-duplicate";
    const string GLYPHICON_PIGGY_BANK = "glyphicon-piggy-bank";
    const string GLYPHICON_SCISSORS = "glyphicon-scissors";
    const string GLYPHICON_BITCOIN = "glyphicon-bitcoin";
    const string GLYPHICON_YEN = "glyphicon-yen";
    const string GLYPHICON_RUBLE = "glyphicon-ruble";
    const string GLYPHICON_SCALE = "glyphicon-scale";
    const string GLYPHICON_ICE_LOLLY = "glyphicon-ice-lolly";
    const string GLYPHICON_ICE_LOLLY_TASTED = "glyphicon-ice-lolly-tasted";
    const string GLYPHICON_EDUCATION = "glyphicon-education";
    const string GLYPHICON_OPTION_HORIZONTAL = "glyphicon-option-horizontal";
    const string GLYPHICON_OPTION_VERTICAL = "glyphicon-option-vertical";
    const string GLYPHICON_MENU_HAMBURGER = "glyphicon-menu-hamburger";
    const string GLYPHICON_MODAL_WINDOW = "glyphicon-modal-window";
    const string GLYPHICON_OIL = "glyphicon-oil";
    const string GLYPHICON_GRAIN = "glyphicon-grain";
    const string GLYPHICON_SUNGLASSES = "glyphicon-sunglasses";
    const string GLYPHICON_TEXT_SIZE = "glyphicon-text-size";
    const string GLYPHICON_TEXT_COLOR = "glyphicon-text-color";
    const string GLYPHICON_TEXT_BACKGROUND = "glyphicon-text-background";
    const string GLYPHICON_OBJECT_ALIGN_TOP = "glyphicon-object-align-top";
    const string GLYPHICON_OBJECT_ALIGN_BOTTOM = "glyphicon-object-align-bottom";
    const string GLYPHICON_OBJECT_ALIGN_HORIZONTAL = "glyphicon-object-align-horizontal";
    const string GLYPHICON_OBJECT_ALIGN_LEFT = "glyphicon-object-align-left";
    const string GLYPHICON_OBJECT_ALIGN_VERTICAL = "glyphicon-object-align-vertical";
    const string GLYPHICON_OBJECT_ALIGN_RIGHT = "glyphicon-object-align-right";
    const string GLYPHICON_TRIANGLE_RIGHT = "glyphicon-triangle-right";
    const string GLYPHICON_TRIANGLE_LEFT = "glyphicon-triangle-left";
    const string GLYPHICON_TRIANGLE_BOTTOM = "glyphicon-triangle-bottom";
    const string GLYPHICON_TRIANGLE_TOP = "glyphicon-triangle-top";
    const string GLYPHICON_CONSOLE = "glyphicon-console";
    const string GLYPHICON_SUPERSCRIPT = "glyphicon-superscript";
    const string GLYPHICON_SUBSCRIPT = "glyphicon-subscript";
    const string GLYPHICON_MENU_LEFT = "glyphicon-menu-left";
    const string GLYPHICON_MENU_RIGHT = "glyphicon-menu-right";
    const string GLYPHICON_MENU_DOWN = "glyphicon-menu-down";
    const string GLYPHICON_MENU_UP = "glyphicon-menu-up";

    /** Containers */
    const string CONTAINER = "container";
    const string CONTAINER_FLUID = "container-fluid";

    /** Sizes */
    const string EXTRA_SMALL = "xs";    // <768 px width
    const string SMALL = "sm";            // <992
    const string MEDIUM = "md";        // <1200
    const string LARGE = "lg";            // > 1200
    const string PRINT_SIZE = "print";    // printing only

    /** Text Classes */
    const string TEXT_LEFT = "text-left";
    const string TEXT_CENTER = "text-center";
    const string TEXT_RIGHT = "text-right";
    const string TEXT_JUSTIFY = "text-justify";
    const string TEXT_NOWRAP = "text-nowrap";

    const string TEXT_LOWERCASE = "text-lowercase";
    const string TEXT_UPPERCASE = "text-uppercase";
    const string TEXT_CAPITALIZE = "text-capitalize";

    const string TEXT_MUTED = "text-muted";
    const string TEXT_PRIMARY = "text-primary";
    const string TEXT_SUCCESS = "text-success";
    const string TEXT_INFO = "text-info";
    const string TEXT_WARNING = "text-warning";
    const string TEXT_DANGER = "text-danger";

    /** List Classes */
    const string LIST_UNSTYLED = "list-unstyled";
    const string LIST_INLINE = "list-inline";

    /** Table Classes */
    const string TABLE = "table";
    const string TABLE_STRIPED = "table-striped";
    const string TABLE_BORDERED = "table-bordered";
    const string TABLE_HOVER = "table-hover";
    const string TABLE_CONDENSED = "table-condensed";
    const string TABLE_RESPONSIVE = "table-responsive";

    /** Contextual Classes */
    const string ACTIVE = "active";
    const string SUCCESS = "success";
    const string WARNING = "warning";
    const string DANGER = "danger";
    const string INFO = "info";

    /** Forms */
    const string FORM_GROUP = "form-group";
    const string FORM_INLINE = "form-inline";
    const string FORM_HORIZONTAL = "form-horizontal";
    const string FORM_CONTROL = "form-control";
    const string FORM_CONTROL_STATIC = "form-control-static";
    const string FORM_CONTROL_FEEDBACK = "form-control-feedback";

    /** Heights within a form group */
    const string FORM_GROUP_LARGE = "form-group-lg";
    const string FORM_GROUP_SMALL = "form-group-sm";

    const string INPUT_GROUP = "input-group";
    const string INPUT_GROUP_ADDON = "input-group-addon";
    const string INPUT_GROUP_LARGE = "input-group-lg";
    const string INPUT_GROUP_MEDIUM = ""; // default
    const string INPUT_GROUP_SMALL = "input-group-sm";

    const string INPUT_LARGE = "input-lg";
    const string INPUT_SMALL = "input-sm";

    const string BUTTON = "btn";
    const string BUTTON_DEFAULT = "btn-default";
    const string BUTTON_PRIMARY = "btn-primary";
    const string BUTTON_SUCCESS = "btn-success";
    const string BUTTON_INFO = "btn-info";
    const string BUTTON_WARNING = "btn-warning";
    const string BUTTON_DANGER = "btn-danger";
    const string BUTTON_LINK = "btn-link";
    const string BUTTON_LARGE = "btn-lg";
    const string BUTTON_MEDIUM = ""; // default
    const string BUTTON_SMALL = "btn-sm";
    const string BUTTON_EXTRA_SMALL = "btn-xs";

    const string CHECKBOX = "checkbox";
    const string CHECKBOX_INLINE = 'checkbox-inline';
    const string RADIO_INLINE = 'radio-inline';


    const string CONTROL_LABEL = "control-label";

    const string HAS_WARNING = "has-warning";
    const string  HAS_ERROR = "has-error";
    const string HAS_SUCCESS = "has-success";
    const string HAS_FEEDBACK = "has-feedback"; // feedback icon will be included

    const string GLYPHICON = "glyphicon";
    const string CLOSE_ICON = "close";
    const string CARET_ICON = "caret";

    const string SCREEN_READER_ONLY = "sr-only"; // class to only use this object in screen readers and hide for everyone else
    const string SCREEN_READER_FOCUSABLE = "sr-only-focusable";

    /** Backgrounds */
    const string BACKGROUND_PRIMARY ="bg-primary";
    const string BACKGROUND_SUCCESS ="bg-success";
    const string BACKGROUND_INFO ="bg-info";
    const string BACKGROUND_WARNING ="bg-warning";
    const string BACKGROUND_DANGER ="bg-danger";

    /** Alignment */
    const string PULL_LEFT = 'pull-left';
    const string PULL_RIGHT = 'pull-right';
    const string CENTER_BLOCK = 'center-block';

    /** Toggling */
    const string HIDDEN = 'hidden';
    const string VISIBLE = 'visible';

    const string BLOCK = 'block';
    const string INLINE = 'inline';
    const string INLINE_BLOCK = 'inline-block';

    /** Nav */

    const string NAV = "nav";
    const string NAV_TABS = "nav-tabs";
    const string NAV_PILLS = "nav-pills";
    const string NAV_JUSTIFIED = "nav-justified";

    /** Navbar */

    const string NAVBAR = 'navbar';

    const string NAVBAR_DEFAULT = 'navbar-default';    // black on white
    const string NAVBAR_INVERSE = 'navbar-inverse'; // white on black

    const string NAVBAR_HEADER = 'navbar-header';
    const string NAVBAR_COLLAPSE = 'navbar-collapse';

    const string NAVBAR_BRAND = 'navbar-brand';
    const string NAVBAR_TOGGLE = 'navbar-toggle';

    const string NAVBAR_NAV = 'navbar-nav';

    const string NAVBAR_LEFT = 'navbar-left';
    const string NAVBAR_RIGHT = 'navbar-right';
    const string NAVBAR_FORM = 'navbar-form';

    /* Panels */
    const string PANEL = 'panel';
    const string PANEL_DEFAULT = 'panel-default';
    const string PANEL_PRIMARY = 'panel-primary';
    const string PANEL_WARNING = 'panel-warning';
    const string PANEL_DANGER = 'panel-danger';
    const string PANEL_SUCCESS = 'panel-success';
    const string PANEL_INFO = 'panel-info';
    const string PANEL_HEADING = 'panel-heading';
    const string PANEL_TITLE = 'panel-title';
    const string PANEL_COLLAPSE = 'panel-collapse';
    const string PANEL_BODY = 'panel-body';
    const string PANEL_FOOTER = 'panel-footer';
    const string PANEL_GROUP = 'panel-group';

    /* Alerts */
    const string ALERT = 'alert';
    const string ALERT_SUCCESS = 'alert-success';
    const string ALERT_INFO = 'alert-info';
    const string ALERT_WARNING = 'alert-warning';
    const string ALERT_DANGER = 'alert-danger';
    const string ALERT_DISMISSABLE = 'alert-dismissable';

    /** Misc */
    const string ROW = 'row';
    const string CLEAR_FIX = 'clearfix';
    const string TEXT_HIDE = 'text-hide';

    /** Modal */
    const string MODAL_LARGE = 'modal-lg';
    const string MODAL_SMALL = 'modal-sm';


    /** Utility methods */

    /**
     * Builds a class used for toggling the visibility of content at different breakpoints.
     *
     * @param bool $blnVisible	True if this is one that shows an object. False for a hidden object
     * @param string $strDeviceSize One of xs, sm, md, lg or print
     * @param null|string $strDisplayType block, inline-block or inline
     * @return string
     */
    public static function createVisibilityClass(bool $blnVisible, string $strDeviceSize, ?string $strDisplayType = null): string
    {
        $strClass = $blnVisible ? Bootstrap::VISIBLE : Bootstrap::HIDDEN;
        $strClass .= '-' . $strDeviceSize;
        if ($blnVisible) {
            assert($strDisplayType);
            $strClass .= $strDisplayType;
        }
        return $strClass;
    }

    /**
     * Constructs a Bootstrap-compatible column class string based on the specified parameters.
     * This function can generate classes for column size, offset, and push/pull functionality for a given device size.
     *
     * @param string $strDeviceSize The target device size (e.g., 'sm', 'md', 'lg', 'xl').
     * @param int $intColumns The number of column grid units to use (0 for none).
     * @param int $intOffset The number of column grid units to offset (0 for none).
     * @param int $intPush The number of column grid units to push (positive values) or pull (negative values) (0 for none).
     *
     * @return string The constructed column class string.
     */
    public static function createColumnClass(string $strDeviceSize, int $intColumns = 0, int $intOffset = 0, int $intPush = 0): string
    {
        $strClass = '';
        if ($intColumns) {
            $strClass = 'col-' . $strDeviceSize . '-' . $intColumns . ' ';
        }

        if ($intOffset) {
            $strClass .= 'col-' . $strDeviceSize . '-offset-' . $intOffset . ' ';
        }

        if ($intPush) {
            if ($intPush > 0) {
                $strClass .= 'col-' . $strDeviceSize . '-push-' . $intPush;
            } else {
                $strClass .= 'col-' . $strDeviceSize . '-pull-' . -$intPush;
            }
        }
        return trim($strClass);
    }

    /**
     * Creates HTML for a Bootstrap glyphicon with an optional screen reader description.
     *
     * This method generates the necessary HTML for displaying a glyphicon icon in a Bootstrap-based UI.
     * If a description is provided, it adds a screen-reader-only span for accessibility purposes.
     *
     * @param string $strIcon The name of the glyphicon class to use (e.g., 'glyphicon-home').
     * @param string|null $strDescription An optional description for screen readers.
     *
     * @return string The generated HTML string for the glyphicon.
     */
    public static function createGlyphHtml(string $strIcon, ?string $strDescription = null): string
    {
        $strToReturn = sprintf('<span class="glyphicon %s" aria-hidden="true"></span>', $strIcon);
        if ($strDescription) {
            $strToReturn .= sprintf('<span class="sr-only">%s</span>', $strDescription);
        }
        return $strToReturn;
    }

    /**
     * Load the JavaScript files required for bootstrap compatibility with qcubed. This should be called by bootstrap
     * widgets that depend on the bootstrap JavaScript.
     *
     * If you are using bootstrap on forms that do not include the bootstrap widgets
     * in this plugin, then the code below will not be executed to load the bootstrap as a file on those forms. You
     * should instead include both files below in your QForm JavaScript files to autoload by overloading
     * GetFormJavaScripts in your QForm class.
     *
     * @param ControlBase $objControl
     *
     * @throws Caller
     */
    public static function loadJS(ControlBase $objControl): void
    {
        $objControl->addJavascriptFile(QCUBED_BOOTSTRAP_JS);
        $objControl->addJavascriptFile(QCUBED_BOOTSTRAP_ASSETS_URL . '/js/qshim.js'); // for jquery ui compatibility
    }
}
